### ISSUE TITLE
Footprints associations 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-sequelize#2]
Implement methods for footprints associations.

**Comment by tjwebb** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33960288)](https://www.bountysource.com/issues/33960288-footprints-associations?utm_source=33960288&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by tjwebb** [comment]
Bounty increased to $150

**Comment by PlasmaPower** [comment]
To clarify, an implementation of this would consist solely of a FootprintService.js (and folders + index.js) like [this one](https://github.com/trailsjs/trailpack-waterline/blob/master/api/services/FootprintService.js), correct?

**Comment by jaumard** [comment]
@PlasmaPower yes at the end OneToOne, OneToMany, ManyToMany associations have to works with `createAssociation, updateAssociation, findAssociation, destroyAssociation` of the FootprintService with all tests to validate it's working. 

Some tests are already done for this module and yes it use SQLite, normally you don't need to remove the DB because the migration is set to drop so all is clear each time. (https://github.com/trailsjs/trailpack-sequelize/blob/master/test/services/FootprintService.test.js#L137-L243) for now tests doesn't cover every associations type so some need to be created. 

Hope it's more clear now :) if not let us know.

**Comment by PlasmaPower** [comment]
@jaumard Makes sense - I'll begin work on this :).

**Comment by jaumard** [comment]
@PlasmaPower great ! Yeah all is set up normally just the sequelize implementation is missing for the FootprintService :)

**Comment by PlasmaPower** [comment]
@tjwebb, Could you look over my PR for this? I think it's done.
