### ISSUE TITLE
Posts same value on unique column twice make the second request hang

### ISSUE THREAD

**Issue by wongyouth** [trailsjs/trailpack-sequelize#35]
I have a User model with unique set on login column.

```js
  static schema (app, Sequelize) {
    return {
      login: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false
      },
  }
```

And use `footprints` to test User model
When I post 2 requests with same data, the second request hangs until timeout.

**Comment by jaumard** [comment]
Hi @wongyouth ! Strange behavior, did you have your project hosted somewhere ? Or can you create a small one in order to reproduce the problem ? I never had this problem before

**Comment by wongyouth** [comment]
I think https://github.com/trailsjs/trailpack-sequelize/blob/master/api/services/FootprintService.js#L49 Error shouldn't be catched. It's expected to be handled on FootprintController

**Comment by jaumard** [comment]
Ok I just test and can reproduce the problem, but's it's not where you say. The bug is under trailpack-express the controller doesn't end the request correctly. I'll try to fix it asap

**Comment by jaumard** [comment]
@wongyouth I just push a fix on trailpack-express, can you test with the master branch and let me know if it fix your issue please ?

**Comment by wongyouth** [comment]
@jaumard It fixed! Thank for your quick reply.
