### ISSUE TITLE
Update sequelize to v4

### ISSUE THREAD

**Issue by themyth92** [trailsjs/trailpack-sequelize#36]
Hi, sequelize has recently been updated to v4. Any plan to update the trailpack-sequelize to use the latest version ?

**Comment by jaumard** [comment]
No plan for now but it's definitely something that we want/must do, but a lot of breaking changes to take into account http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html so it need some time (that I don't have for now)
PR are welcome if you have time :)

**Comment by jaumard** [comment]
close by #37
